version: "3.2"
services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - optima
    ports:
      - 6379:6379

networks:
  optima:
    external: true