# version: "3.8"
services:
  db_general:
    image: mariadb:latest
    container_name: datacenter
    restart: unless-stopped
    networks:
      - optima
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    volumes:
      - ./config/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      - ./data:/home
    ports:
      - 3307:3306

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    networks:
      - optima
    ports:
      - 8008:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_general:

networks:
  optima:
    external: true